In [2]:
a = np.matrix('1 0 0; 0 1 0; 0 0 1')

In [3]:
a

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [4]:
a.H

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [5]:
b=np.array([[1,5],[3,2],[5,6]])

In [6]:
b

array([[1, 5],
       [3, 2],
       [5, 6]])

In [7]:
x = np.matrix(b)

In [8]:
x

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [9]:
a.dot(b)

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [10]:
np.dot(a,b)

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [11]:
np.cross(a,b)

array([[ 0,  0,  5],
       [ 0,  0, -3],
       [-6,  5,  0]])

In [12]:
np.linalg.det(a)

1.0

In [13]:
np.linalg.eig(a)[0]

array([1., 1., 1.])

In [18]:
vec1 = np.array([1, 2, 3])
print(vec1)

[1 2 3]


In [34]:
vec2 = np.array([[3, 2], [2, 1], [1, 0]])
print(vec2)
vec2 = vec2.transpose()
print(vec2)

[[3 2]
 [2 1]
 [1 0]]
[[3 2 1]
 [2 1 0]]


In [35]:
vec1 * vec2

array([[3, 4, 3],
       [2, 2, 0]])

In [36]:
vec2 * vec1

array([[3, 4, 3],
       [2, 2, 0]])

In [38]:
vec1.diagonal()

ValueError: diag requires an array of at least two dimensions