In [3]:
from numpy import *

In [4]:
a = arange(15).reshape(3, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray

In [12]:
b = array([6, 7, 8])

In [13]:
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

In [15]:
a = array([2, 3, 4])

In [16]:
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b = array([1.2, 3.5, 5.1])

In [19]:
b.dtype

dtype('float64')

***
#### this will cause error
a = array(1, 2, 3, 4)

---------------------------------------------------------------------------<br>
ValueError                                Traceback (most recent call last)<br>
`<ipython-input-40-ecd64be9c632>` in `<module>`()<br> 
----> a = array(1, 2, 3, 4)<br>
<br>
ValueError: only 2 non-keyword arguments accepted<br>
***

In [20]:
a = array([1, 2, 3, 4])

In [21]:
b = array([(1.5, 2, 3), (4, 5, 6)])

In [22]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
c = array([[1, 2], [3, 4]], dtype=complex)

In [24]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [25]:
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
ones((2,3,4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [27]:
empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [28]:
arange(10, 30, 5)

array([10, 15, 20, 25])

In [29]:
arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])

In [30]:
arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
a = arange(6)

In [32]:
a

array([0, 1, 2, 3, 4, 5])

In [33]:
b = arange(12).reshape(4, 3)

In [34]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
c = arange(24).reshape(2, 3, 4)

In [36]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c = arange(24).reshape(3, 2, 4)

In [38]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
c = arange(24).reshape(3, 4, 2)

In [40]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [42]:
np.linalg(np.matrix(c))

ValueError: shape too large to be a matrix.