In [36]:
import numpy as np
import random

In [37]:
def getRandArr():
    a = []
    for i in range(10):
        a.append(random.randint(0,10))
    return a

def printArgmax(arr, ax=0):
    print(len(arr))
    print(np.argmax(arr, axis=ax))

In [38]:
arr = getRandArr()
print(arr)
printArgmax(arr)

[2, 8, 2, 5, 10, 3, 6, 3, 10, 10]
10
4


In [39]:
b = []
for i in range(10):
    b.append(getRandArr())

b = np.array(b)
print(b)
printArgmax(b, ax=0)
printArgmax(b, ax=1)

[[ 2  2  4  5  5  0  3  3  7  2]
 [ 8  1  7  5  2  0 10  6  5  0]
 [ 5  7  8  6  8  1  8  6  2  3]
 [ 8  5  9  8  9  2  4  8  7  1]
 [10  2  0 10  3  7  7 10  2  8]
 [ 8  5  1  6  7  9  3  2  5  3]
 [ 4  7  1  1  3  4  6  8  0  1]
 [ 6  8 10  9  5 10 10  2  4  3]
 [10  4 10  3  0  8  9  7  2  3]
 [ 3  9  1  4  1  1  7  2  2  0]]
10
[4 9 7 4 3 7 1 4 0 4]
10
[8 6 2 2 0 5 7 2 0 1]


In [42]:
c = []
for i in range(10):
    d = []
    for j in range(10):
        d.append(getRandArr())
    c.append(d)

c = np.array(c)
print(c)
printArgmax(c, ax=0)
printArgmax(c, ax=1)
printArgmax(c, ax=2)

[[[ 8  5  7  5  4  8 10  9  7  8]
  [ 1  6  9  5  6  4 10  9  1  3]
  [ 2  5  5  4 10  4  1  4  1 10]
  [ 1 10  4  6  2  0  0  8  4  0]
  [10  8  5  2  8  7  8  3  6  1]
  [10  7  0  7  2  3  4  9  1  9]
  [ 7  9  2  2  5  6  3  1  7  5]
  [ 2  4 10  1  2  6  6  2  9  6]
  [ 9  0  4  7  4 10  7  4  2  2]
  [10  4  7 10  8  6  5 10  2  7]]

 [[ 5  6  2  1  1  6  9  0  6  6]
  [ 4  9  3  6  1  3  9  6  6  5]
  [ 5  3  3  9  4  4  2  7  2  5]
  [10  0 10  8  1  8  4  9  2  5]
  [ 5  0  3 10  3 10 10  2  2  5]
  [ 0  1  0  5  1 10  8  7  9  8]
  [ 4  9  5  5  7  7  6  6  0  0]
  [ 6  2  3  4  2 10  3  6  8  7]
  [ 8  9  0  7  6  8  8 10 10  0]
  [ 3  9  9  9 10  1  6  2  8  3]]

 [[ 3  3  1  6  0  7  4  7  1  5]
  [ 6  1 10  6  6  4  3  6 10  7]
  [ 5 10  9 10  0  4  7  6  0  1]
  [ 2  6  4  8  3  2 10  2  8  7]
  [ 6  1  2  3  8  0  4  8  5  1]
  [ 2  8  5  6  4  0  4 10  0  4]
  [ 7 10  7  9  7  0  8 10  4 10]
  [ 3  3  1  8  5  4  5  0  3  6]
  [10  9  1  9  8  1 10 10  5  9]
  [ 0  7  