In [2]:
a = np.matrix('1 0 0; 0 1 0; 0 0 1')

In [3]:
a

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [4]:
a.H

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [6]:
b=np.array([[1,5],[3,2],[5,6]])

In [7]:
b

array([[1, 5],
       [3, 2],
       [5, 6]])

In [8]:
x = np.matrix(b)

In [9]:
x

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [12]:
a.dot(b)

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [16]:
np.dot(a,b)

matrix([[1, 5],
        [3, 2],
        [5, 6]])

In [15]:
np.cross(a,b)

array([[ 0,  0,  5],
       [ 0,  0, -3],
       [-6,  5,  0]])

In [5]:
np.linalg.det(a)

1.0

In [14]:
np.linalg.eig(a)[0]

array([1., 1., 1.])